### ISSUE TITLE
Java heap space error when trying to run

### ISSUE THREAD

**Issue by dietergeerts** [SonarSource/sonarjs-cli#13]
I got the following error when trying to run sonarjs:

```
Exception in thread "main"
java.lang.OutOfMemoryError: Java heap space
        at org.sonar.sslr.internal.matchers.ParseNode.<init>(ParseNode.java:39)
        at org.sonar.sslr.internal.vm.Machine.createNode(Machine.java:256)
        at org.sonar.sslr.internal.vm.Instruction$RetInstruction.execute(Instruction.java:305)
        at org.sonar.sslr.internal.vm.Machine.execute(Machine.java:162)
        at org.sonar.sslr.internal.vm.Machine.execute(Machine.java:105)
        at org.sonar.sslr.internal.vm.Machine.parse(Machine.java:83)
        at org.sonar.sslr.parser.ParseRunner.parse(ParseRunner.java:46)
        at com.sonar.sslr.api.typed.ActionParser.parse(ActionParser.java:101)
        at com.sonar.sslr.api.typed.ActionParser.parse(ActionParser.java:97)
        at org.sonar.javascript.parser.JavaScriptParser.parse(JavaScriptParser.java:50)
        at org.sonar.javascript.parser.JavaScriptParser.parse(JavaScriptParser.java:30)
        at org.sonar.plugins.javascript.JavaScriptSensor.analyse(JavaScriptSensor.java:161)
        at org.sonar.plugins.javascript.JavaScriptSensor.analyseFiles(JavaScriptSensor.java:131)
        at org.sonar.plugins.javascript.JavaScriptSensor.execute(JavaScriptSensor.java:325)
        at org.sonarsource.sonarlint.core.analyzer.sensor.NewSensorsExecutor.executeSensor(NewSensorsExecutor.java:72)
        at org.sonarsource.sonarlint.core.analyzer.sensor.NewSensorsExecutor.execute(NewSensorsExecutor.java:63)
        at org.sonarsource.sonarlint.core.analyzer.sensor.PhaseExecutor.execute(PhaseExecutor.java:36)
        at org.sonarsource.sonarlint.core.container.analysis.AnalysisContainer.doAfterStart(AnalysisContainer.java:142)
        at org.sonarsource.sonarlint.core.container.ComponentContainer.startComponents(ComponentContainer.java:125)
        at org.sonarsource.sonarlint.core.container.ComponentContainer.execute(ComponentContainer.java:110)

        at org.sonarsource.sonarlint.core.container.standalone.StandaloneGlobalContainer.analyze(StandaloneGlobalContainer.java:127)
        at org.sonarsource.sonarlint.core.StandaloneSonarLintEngineImpl.analyze(StandaloneSonarLintEngineImpl.java:91)
        at org.sonarsource.mini.scanner.analysis.StandaloneSonarLint.doAnalysis(StandaloneSonarLint.java:70)
        at org.sonarsource.mini.scanner.analysis.StandaloneSonarLint.runAnalysis(StandaloneSonarLint.java:57)
        at org.sonarsource.mini.scanner.Main.runOnce(Main.java:79)
        at org.sonarsource.mini.scanner.Main.run(Main.java:60)
        at org.sonarsource.mini.scanner.Main.execute(Main.java:94)
        at org.sonarsource.mini.scanner.Main.main(Main.java:84)

Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "Report about progress of Javascript analyzer"
```

**Comment by vilchik-elena** [comment]
Hi!
You probably have some file with a lot of nesting syntax. Do you analyse any generated code?
Anyway, sorry to tell you that, we are not maintaining this tool anymore.
Now you are recommended to either fully use SQ with SonarJS installed there or use ESLint extension: https://github.com/SonarSource/eslint-plugin-sonarjs

**Comment by dietergeerts** [comment]
Thx, the eslint plugin does work.
